name: Deploy Grid+AI Demo

on:
  push:
    branches: [ next ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          cache: 'npm' # Кэширование node_modules

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker registry
      - name: Login to Webix Registry
        uses: docker/login-action@v3
        with:
          registry: registry.webix.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: registry.webix.io/grid-ai-demo:next
          build-args: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
            CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}